#ifndef KEYBOARD_TOOLS_WIN_EVENT_CONVERTER_HPP
#define KEYBOARD_TOOLS_WIN_EVENT_CONVERTER_HPP

#include <windows.h>

#include <keyboard_tools/types.hpp>

namespace kbdt
{

namespace details
{

/**
 * @param uuid A special value attached to the event that can be used for distinguish
 * whether the event was generated by this program.
 */
INPUT keyEventToInput(const KeyEvent& event, uint64_t uuid);

KeyEvent keyEventFromParam(WPARAM wParam, LPARAM lParam);

} // namespace details

} // namespace kbdt

#endif // !KEYBOARD_TOOLS_WIN_EVENT_CONVERTER_HPP
