#include <keyboard_tools_details.hpp>

#include <windows.h>

#include <uuid.hpp>
#include "event_converter.hpp"

namespace kbt
{

namespace details
{

#define WM_SET_EVENT_HANDLER (WM_USER + 1)

static KeyEventHandler eventHandler = nullptr;
static DWORD workerThreadId = 0;

static LRESULT WINAPI LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode == HC_ACTION)
    {
        KBDLLHOOKSTRUCT* kbdllhs = reinterpret_cast<KBDLLHOOKSTRUCT*>(static_cast<intptr_t>(lParam));
        // If the event is generated by this program or no event handler is set, pass it to the next hook.
        if (kbdllhs->dwExtraInfo == static_cast<ULONG_PTR>(uuid()) || !eventHandler)
            return CallNextHookEx(nullptr, nCode, wParam, lParam);

        KeyEvent event = keyEventFromParam(wParam, lParam);
        if (!eventHandler(event))
            return 1;
    }
    return CallNextHookEx(nullptr, nCode, wParam, lParam);
}

int initialize()
{
    return KBT_RC_SUCCESS;
}

int stopWork()
{
    if (PostThreadMessageA(workerThreadId, WM_DESTROY, 0, 0) != 0)
        return KBT_RC_SUCCESS;
    return GetLastError();
}

int setEventHandler(KeyEventHandler handler)
{
    if (PostThreadMessageA(workerThreadId, WM_SET_EVENT_HANDLER, reinterpret_cast<WPARAM>(handler), 0) != 0)
        return KBT_RC_SUCCESS;
    return GetLastError();
}

void work()
{
    HHOOK kbdHook = SetWindowsHookExA(WH_KEYBOARD_LL, &LowLevelKeyboardProc, nullptr, 0);
    if (!kbdHook)
    {
        setRunFail(GetLastError());
        return;
    }

    workerThreadId = GetCurrentThreadId();
    MSG msg = {0};
    // Force the system to create the message queue.
    PeekMessageA(&msg, nullptr, WM_USER, WM_USER, PM_NOREMOVE);
    // Indicate the worker thread is created successfully after create the message queue.
    // This can ensure that the `PostThreadMessage()` be performed only when the message queue exists.
    setRunSuccess();

    // Retrieves only messages on the current thread's message queue whose hwnd value is NULL.
    // In this case the thread message as posted by `PostThreadMessage()`.
    while (GetMessageA(&msg, reinterpret_cast<HWND>(static_cast<intptr_t>(-1)), 0, 0) != 0)
    {
        if (msg.message == WM_DESTROY)
            PostQuitMessage(0);
        else if (msg.message == WM_SET_EVENT_HANDLER)
            eventHandler = reinterpret_cast<KeyEventHandler>(static_cast<intptr_t>(msg.wParam));
    }

    UnhookWindowsHookEx(kbdHook);

    eventHandler = nullptr;
    workerThreadId = 0;
}

} // namespace details

} // namespace kbt
