#ifndef KEYBOARD_TOOLS_MAC_EVENT_CONVERTER_HPP
#define KEYBOARD_TOOLS_MAC_EVENT_CONVERTER_HPP

#include <CoreGraphics/CGEvent.h>

#include <keyboard_tools/types.hpp>

namespace kbdt
{

namespace details
{

/**
 * @param uuid A special value attached to the event that can be used for distinguish
 * whether the event was generated by this program.
 */
CGEventRef keyEventToCGEvent(const KeyEvent& event, uint64_t uuid);

KeyEvent keyEventFromCGEvent(CGEventType cgEventType, CGEventRef cgEvent);

} // namespace details

} // namespace kbdt

#endif // !KEYBOARD_TOOLS_MAC_EVENT_CONVERTER_HPP
